---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://github.com/<your_GitHub_username>
  type: git
  password: <your personal_access_token>
  username: <your_GitHub_username>
